#!/usr/bin/env bash

# sitelen2pseudo by Jeremy Reeder
# https://github.com/jeremyreeder/wawa-toki-pona

sitelen_pona_ucsur='󱤀󱤁󱤂󱤃󱤄󱤅󱤆󱤇󱤈󱤉󱤊󱤋󱤌󱤍󱤎󱤏󱤐󱤑󱤒󱤓󱤔󱤕󱤖󱤗󱤘󱤙󱤚󱤛󱤜󱤝󱤞󱤟󱤠󱤡󱤢󱤣󱤤󱤥󱤦󱤧󱤨󱤩󱤪󱤫󱤬󱤭󱤮󱤯󱤰󱤱󱤲󱤳󱤴󱤵󱤶󱤷󱤸󱤹󱤺󱤻󱤼󱤽󱤾󱤿󱥀󱥁󱥂󱥃󱥄󱥅󱥆󱥇󱥈󱥉󱥊󱥋󱥌󱥍󱥎󱥏󱥐󱥑󱥒󱥓󱥔󱥕󱥖󱥗󱥘󱥙󱥚󱥛󱥜󱥝󱥞󱥟󱥠󱥡󱥢󱥣󱥤󱥥󱥦󱥧󱥨󱥩󱥪󱥫󱥬󱥭󱥮󱥯󱥰󱥱󱥲󱥳󱥴󱥵󱥶󱥷󱥸󱥹󱥺󱥻󱥼󱥽󱥾󱥿󱦀󱦁󱦂󱦃󱦄󱦅󱦆󱦇󱦈󱦐󱦑󱦠󱦡󱦢󱦣'
pseudo_sitelen_uni='ȧӫX⭄∞⫧⩆Yᐲ≫+£O⌒Ⴔ⟓இጻᐂĠᨇᗢᐼꕚKਨద♢ಐ∬🜁🝆ᑔ)⊸Ϫ⦵ᚃ⚹>v~⎕⊼∸ᕆ⚆⋃🜨ඉᗨ⍝ᑭ⍜ቪ⏕⫣⚟☽☋ꔖ#𖦹⫛ᑎ↓▭ᕊoოᓄ𝈣⍯󱥉𝄦󱥋ᕇL♡⨻ꕯⴶᒳ󱥓◡⌻=ᗐ󱥘?⫨𝍰⌾⫠ᑲ⊩ꘖ⏍ᕈV🝊π^↶⫞ᐽ≈◷⛣⌂ⅡᏈᗜ⚔ꕖ1ᔨ‖∷⍵⊹ẋ⩹%⧈෴⚧≉ഫ󱦁H𐌣⦺ᕦn⩉⍃[]⊤󱦡⫟󱦣'
perl -Mopen=locale -Mutf8 -CSAD -pe "tr/${sitelen_pona_ucsur}/${pseudo_sitelen_uni}/"
